services: 
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - imobiliaria_terreno_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend-net

  backend:
    build: .
    container_name: backend
    ports: 
      - ${APP_PORT}:${APP_PORT}
    environment: 
      APP_PORT: ${APP_PORT}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_HOST: ${POSTGRES_HOST} 
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - backend-net

volumes:
  imobiliaria_terreno_db:

networks:
  backend-net:
    driver: bridge
