services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - kozempa_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend-net

volumes:
  kozempa_db:

networks:
  backend-net:
    driver: bridge
