package seeder

import (
	"fmt"
	"main/domain/entities"
	"math/rand"

	"gorm.io/gorm"
)

func SeedProperties(db *gorm.DB) {
	err := db.Exec("TRUNCATE TABLE properties RESTART IDENTITY CASCADE").Error
	if err != nil {
		fmt.Printf("failed to truncate table properties: %v\n", err)
	}

	properties := []entities.Property{
		{
			Size:                uint(rand.Float64()*500 + 50),
			Rooms:               uint(rand.Float64()*6 + 1),
			Kitchens:            uint(rand.Float64()*3 + 1),
			Bathrooms:           uint(rand.Float64()*4 + 1),
			Address:             "Avenida Paraná, 123, Umuarama, PR",
			Summary:             "Ótima localização comercial, próximo ao centro.",
			Details:             "Imóvel bem conservado com fácil acesso a mercados, farmácias e bancos.",
			Latitude:            -23.766667,
			Longitude:           -53.320556,
			Price:               rand.Float64()*1000000 + 50000,
			Discount:            rand.Float64() * 50000,
			IsSold:              rand.Float64() >= 0.5,
			IsHighlight:         rand.Float64() >= 0.8,
			ConstructionYear:    uint(rand.Float64()*50 + 1970),
			KindID:              uint(rand.Float64()*5 + 1),
			StatusID:            1,
			PaymentTypeID:       uint(rand.Float64()*5 + 1),
			VisitedBy:           []string{generateRandomMD5()},
			NegotiationTypeID:   uint(rand.Float64()*9 + 1),
			UnitOfMeasurementID: uint(rand.Float64()*5 + 1),
			PreviewImages: []string{"fallback.jpg"},
		},
		{
			Size:                uint(rand.Float64()*500 + 50),
			Rooms:               uint(rand.Float64()*6 + 1),
			Kitchens:            uint(rand.Float64()*3 + 1),
			Bathrooms:           uint(rand.Float64()*4 + 1),
			Address:             "Rua Maringá, 456, Umuarama, PR",
			Summary:             "Próximo ao shopping e ao terminal de ônibus.",
			Details:             "Ideal para quem busca praticidade e conforto.",
			Latitude:            -23.763611,
			Longitude:           -53.324167,
			Price:               rand.Float64()*1000000 + 50000,
			Discount:            rand.Float64() * 50000,
			IsSold:              rand.Float64() >= 0.5,
			IsHighlight:         rand.Float64() >= 0.8,
			ConstructionYear:    uint(rand.Float64()*50 + 1970),
			KindID:              uint(rand.Float64()*5 + 1),
			StatusID:            1,
			PaymentTypeID:       uint(rand.Float64()*5 + 1),
			VisitedBy:           []string{generateRandomMD5(), generateRandomMD5()},
			NegotiationTypeID:   uint(rand.Float64()*9 + 1),
			UnitOfMeasurementID: uint(rand.Float64()*5 + 1),
			PreviewImages: []string{"fallback.jpg"},
		},
		{
			Size:                uint(rand.Float64()*500 + 50),
			Rooms:               uint(rand.Float64()*6 + 1),
			Kitchens:            uint(rand.Float64()*3 + 1),
			Bathrooms:           uint(rand.Float64()*4 + 1),
			Address:             "Rua José Honório Ramos, 789, Umuarama, PR",
			Summary:             "Imóvel espaçoso, perfeito para grandes famílias.",
			Details:             "Excelente área de lazer com piscina e churrasqueira.",
			Latitude:            -23.772500,
			Longitude:           -53.325833,
			Price:               rand.Float64()*1000000 + 50000,
			Discount:            rand.Float64() * 50000,
			IsSold:              rand.Float64() >= 0.5,
			IsHighlight:         rand.Float64() >= 0.8,
			ConstructionYear:    uint(rand.Float64()*50 + 1970),
			KindID:              uint(rand.Float64()*5 + 1),
			StatusID:            1,
			PaymentTypeID:       uint(rand.Float64()*5 + 1),
			VisitedBy:           []string{generateRandomMD5(), generateRandomMD5(), generateRandomMD5()},
			NegotiationTypeID:   uint(rand.Float64()*9 + 1),
			UnitOfMeasurementID: uint(rand.Float64()*5 + 1),
			PreviewImages: []string{"fallback.jpg"},
		},
		{
			Size:                uint(rand.Float64()*500 + 50),
			Rooms:               uint(rand.Float64()*6 + 1),
			Kitchens:            uint(rand.Float64()*3 + 1),
			Bathrooms:           uint(rand.Float64()*4 + 1),
			Address:             "Rua Ministro Oliveira Salazar, 101, Umuarama, PR",
			Summary:             "Local tranquilo e seguro, ideal para famílias.",
			Details:             "Próximo a escolas e parques, excelente para crianças.",
			Latitude:            -23.765000,
			Longitude:           -53.318611,
			Price:               rand.Float64()*1000000 + 50000,
			Discount:            rand.Float64() * 50000,
			IsSold:              rand.Float64() >= 0.5,
			IsHighlight:         rand.Float64() >= 0.8,
			ConstructionYear:    uint(rand.Float64()*50 + 1970),
			KindID:              uint(rand.Float64()*5 + 1),
			StatusID:            1,
			PaymentTypeID:       uint(rand.Float64()*5 + 1),
			VisitedBy:           []string{generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5()},
			NegotiationTypeID:   uint(rand.Float64()*9 + 1),
			UnitOfMeasurementID: uint(rand.Float64()*5 + 1),
			PreviewImages: []string{"fallback.jpg"},
		},
		{
			Size:                uint(rand.Float64()*500 + 50),
			Rooms:               uint(rand.Float64()*6 + 1),
			Kitchens:            uint(rand.Float64()*3 + 1),
			Bathrooms:           uint(rand.Float64()*4 + 1),
			Address:             "Rua Alvorada, 234, Umuarama, PR",
			Summary:             "Prédio comercial no centro da cidade.",
			Details:             "Ótima visibilidade e fluxo de pessoas.",
			Latitude:            -23.771111,
			Longitude:           -53.321667,
			Price:               rand.Float64()*1000000 + 50000,
			Discount:            rand.Float64() * 50000,
			IsSold:              rand.Float64() >= 0.5,
			IsHighlight:         rand.Float64() >= 0.8,
			ConstructionYear:    uint(rand.Float64()*50 + 1970),
			KindID:              uint(rand.Float64()*5 + 1),
			StatusID:            1,
			PaymentTypeID:       uint(rand.Float64()*5 + 1),
			VisitedBy:           []string{generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5()},
			NegotiationTypeID:   uint(rand.Float64()*9 + 1),
			UnitOfMeasurementID: uint(rand.Float64()*5 + 1),
			PreviewImages: []string{"fallback.jpg"},
		},
		{
			Size:                uint(rand.Float64()*500 + 50),
			Rooms:               uint(rand.Float64()*6 + 1),
			Kitchens:            uint(rand.Float64()*3 + 1),
			Bathrooms:           uint(rand.Float64()*4 + 1),
			Address:             "Rua Paraná, 345, Umuarama, PR",
			Summary:             "Residência de alto padrão, próxima a shoppings e restaurantes.",
			Details:             "Acabamento de primeira qualidade, mobiliada.",
			Latitude:            -23.768056,
			Longitude:           -53.20278,
			Price:               rand.Float64()*1000000 + 50000,
			Discount:            rand.Float64() * 50000,
			IsSold:              rand.Float64() >= 0.5,
			IsHighlight:         rand.Float64() >= 0.8,
			ConstructionYear:    uint(rand.Float64()*50 + 1970),
			KindID:              uint(rand.Float64()*5 + 1),
			StatusID:            1,
			PaymentTypeID:       uint(rand.Float64()*5 + 1),
			VisitedBy:           []string{generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5()},
			NegotiationTypeID:   uint(rand.Float64()*9 + 1),
			UnitOfMeasurementID: uint(rand.Float64()*5 + 1),
			PreviewImages: []string{"fallback.jpg"},
		},
		{
			Size:                uint(rand.Float64()*500 + 50),
			Rooms:               uint(rand.Float64()*6 + 1),
			Kitchens:            uint(rand.Float64()*3 + 1),
			Bathrooms:           uint(rand.Float64()*4 + 1),
			Address:             "Rua Londrina, 567, Umuarama, PR",
			Summary:             "Terreno amplo para construção residencial ou comercial.",
			Details:             "Localização excelente com fácil acesso a avenidas principais.",
			Latitude:            -23.764167,
			Longitude:           -53.319444,
			Price:               rand.Float64()*1000000 + 50000,
			Discount:            rand.Float64() * 50000,
			IsSold:              rand.Float64() >= 0.5,
			IsHighlight:         rand.Float64() >= 0.8,
			ConstructionYear:    uint(rand.Float64()*50 + 1970),
			KindID:              uint(rand.Float64()*5 + 1),
			StatusID:            1,
			PaymentTypeID:       uint(rand.Float64()*5 + 1),
			VisitedBy:           []string{generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5()},
			NegotiationTypeID:   uint(rand.Float64()*9 + 1),
			UnitOfMeasurementID: uint(rand.Float64()*5 + 1),
			PreviewImages: []string{"fallback.jpg"},
		},
		{
			Size:                uint(rand.Float64()*500 + 50),
			Rooms:               uint(rand.Float64()*6 + 1),
			Kitchens:            uint(rand.Float64()*3 + 1),
			Bathrooms:           uint(rand.Float64()*4 + 1),
			Address:             "Avenida Rio Branco, 789, Umuarama, PR",
			Summary:             "Casa espaçosa com quintal, ótima para pets.",
			Details:             "Bairro calmo, ideal para famílias com crianças.",
			Latitude:            -23.770000,
			Longitude:           -53.322500,
			Price:               rand.Float64()*1000000 + 50000,
			Discount:            rand.Float64() * 50000,
			IsSold:              rand.Float64() >= 0.5,
			IsHighlight:         rand.Float64() >= 0.8,
			ConstructionYear:    uint(rand.Float64()*50 + 1970),
			KindID:              uint(rand.Float64()*5 + 1),
			StatusID:            1,
			PaymentTypeID:       uint(rand.Float64()*5 + 1),
			VisitedBy:           []string{generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5()},
			NegotiationTypeID:   uint(rand.Float64()*9 + 1),
			UnitOfMeasurementID: uint(rand.Float64()*5 + 1),
			PreviewImages: []string{"fallback.jpg"},
		},
		{
			Size:                uint(rand.Float64()*500 + 50),
			Rooms:               uint(rand.Float64()*6 + 1),
			Kitchens:            uint(rand.Float64()*3 + 1),
			Bathrooms:           uint(rand.Float64()*4 + 1),
			Address:             "Rua Bahia, 901, Umuarama, PR",
			Summary:             "Terreno pronto para construção, com documentação regular.",
			Details:             "Área nobre com vista privilegiada.",
			Latitude:            -23.766111,
			Longitude:           -53.326111,
			Price:               rand.Float64()*1000000 + 50000,
			Discount:            rand.Float64() * 50000,
			IsSold:              rand.Float64() >= 0.5,
			IsHighlight:         rand.Float64() >= 0.8,
			ConstructionYear:    uint(rand.Float64()*50 + 1970),
			KindID:              uint(rand.Float64()*5 + 1),
			StatusID:            1,
			PaymentTypeID:       uint(rand.Float64()*5 + 1),
			VisitedBy:           []string{generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5()},
			NegotiationTypeID:   uint(rand.Float64()*9 + 1),
			UnitOfMeasurementID: uint(rand.Float64()*5 + 1),
			PreviewImages: []string{"fallback.jpg"},
		},
		{
			Size:                uint(rand.Float64()*500 + 50),
			Rooms:               uint(rand.Float64()*6 + 1),
			Kitchens:            uint(rand.Float64()*3 + 1),
			Bathrooms:           uint(rand.Float64()*4 + 1),
			Address:             "Av. Padre José Germano Neto, 3218 - Zona VI, Umuarama, PR",
			Summary:             "Terreno com instalação comercial de grande porte.",
			Details:             "Área nobre com clientela fixa.",
			Latitude:            -23.7667942,
			Longitude:           -53.3231817,
			Price:               rand.Float64()*1000000 + 50000,
			Discount:            rand.Float64() * 50000,
			IsSold:              rand.Float64() >= 0.5,
			IsHighlight:         rand.Float64() >= 0.8,
			ConstructionYear:    uint(rand.Float64()*50 + 1970),
			KindID:              uint(rand.Float64()*5 + 1),
			StatusID:            1,
			PaymentTypeID:       uint(rand.Float64()*5 + 1),
			VisitedBy:           []string{generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5(), generateRandomMD5()},
			NegotiationTypeID:   uint(rand.Float64()*9 + 1),
			UnitOfMeasurementID: uint(rand.Float64()*5 + 1),
			PreviewImages: []string{"fallback.jpg"},
		},
	}

	for _, property := range properties {
		db.Create(&property)
	}

	fmt.Println("All properties have been seeded.")
	fmt.Println("----------------------------")
}

func generateRandomMD5() string {
	return fmt.Sprintf("%x", rand.Int63())
}
